
  [[redirects]]
  from = "/*"
  to = "https://zam.zilytst.com/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"



